// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAefbQh76mIAYOcrS30a-SgfBOzEbrf32s',
    appId: '1:921022996019:web:ce637d15d8c993dae04d46',
    messagingSenderId: '921022996019',
    projectId: 'chatapp-5f7b2',
    authDomain: 'chatapp-5f7b2.firebaseapp.com',
    storageBucket: 'chatapp-5f7b2.appspot.com',
    measurementId: 'G-03MD2JQD6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh_028GOrOvNYMZr4wV7tqmfEXgqBpA34',
    appId: '1:921022996019:android:ac53f22eb4ab5df5e04d46',
    messagingSenderId: '921022996019',
    projectId: 'chatapp-5f7b2',
    storageBucket: 'chatapp-5f7b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx_nGT3DmXswLrLhJoS7leGLzO5RZufFs',
    appId: '1:921022996019:ios:e361959978ce23e5e04d46',
    messagingSenderId: '921022996019',
    projectId: 'chatapp-5f7b2',
    storageBucket: 'chatapp-5f7b2.appspot.com',
    iosBundleId: 'com.example.ichat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx_nGT3DmXswLrLhJoS7leGLzO5RZufFs',
    appId: '1:921022996019:ios:2db599bbc3e7de6ce04d46',
    messagingSenderId: '921022996019',
    projectId: 'chatapp-5f7b2',
    storageBucket: 'chatapp-5f7b2.appspot.com',
    iosBundleId: 'com.example.ichat.RunnerTests',
  );
}
